<?php

/**
 * @file
 * Contains axe_test.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function axe_test_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'system_site_information_settings') {
    $config = \Drupal::config('system.site');
    $form['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#default_value' => !empty($config->get('siteapikey')) ? $config->get('siteapikey') : 'No API Key yet',
    ];
    $form['actions']['submit']['#value'] = t('Update Configuration');
    $form['#submit'][] = 'axe_test_site_settings_form_submit';
  }
}

/**
 * {@inheritdoc}
 */
function axe_test_site_settings_form_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $config->set('siteapikey', $form_state->getValue('siteapikey'));
  $config->save();
  if (!empty($form_state->getValue('siteapikey'))) {
    \Drupal::messenger()->addStatus(t("Site API Key has been saved with '@site_api_key' value.", ['@site_api_key' => $form_state->getValue('siteapikey')]));
  }
}
